# Example render.yaml (adjust paths and commands as needed)
services:
  - type: web_service
    name: my-portfolio-api # Name for your backend service
    env: node
    # Root directory of your backend code within the monorepo
    # Assuming your backend is in 'server/'
    rootDir: server/
    buildCommand: npm install
    startCommand: node src/app.js # Or 'npm start' if you have a start script in server/package.json
    # Port your Node.js app listens on (Render automatically sets the PORT env var)
    envVars:
      - key: DATABASE_URL # Environment variable for your database connection string
        value: ${MY_PORTFOLIO_DB.internalConnectionString} # Links to the Render PostgreSQL service
      # Add any other sensitive environment variables here
      # - key: SECRET_KEY
      #   sync: false # Set to false if you want to manually manage this in Render dashboard for production
    autoDeploy: true # Enable auto-deploy on every push to your main branch
    # Free instances may spin down after inactivity
    # plan: free # Specify free plan

  - type: static_site
    name: my-portfolio-frontend # Name for your frontend service
    # Root directory of your frontend code within the monorepo
    # Assuming your frontend is in 'client/'
    rootDir: client/
    buildCommand: npm install && npm run build
    publishPath: client/build # Or client/dist for Vite
    autoDeploy: true # Enable auto-deploy
    # plan: free

  - type: postgres
    name: my-portfolio-db # Name for your PostgreSQL database
    # Default plan is usually enough for free tier
    # plan: free