services:
  - type: web
    name: portfolio-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: client
  - type: web
    name: portfolio-app-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server