# Example render.yaml (adjust paths and commands as needed)
services:
  - type: web
    name: my-portfolio-api # Name for your backend service
    env: node
    # Root directory of your backend code within the monorepo
    # Assuming your backend is in 'server/'
    rootDir: server/
    buildCommand: npm install
    startCommand: npm run migrate:latest && node src/app.js    # Port your Node.js app listens on (Render automatically sets the PORT env var)
    envVars:
      - key: DATABASE_URL # This will hold your Supabase connection string
        sync: false # Set to false to manually add in Render Dashboard for security
      - key: NODE_ENV # Important for Knex to pick 'production' config
        value: production
      # Add any other sensitive environment variables here
      # - key: SECRET_KEY
      #   sync: false # Set to false if you want to manually manage this in Render dashboard for production
    autoDeploy: true # Enable auto-deploy on every push to your main branch
    # Free instances may spin down after inactivity
    # plan: free # Specify free plan

  - type: web
    name: my-portfolio-frontend # Name for your frontend service
    runtime: static # Crucial for static sites when type is 'web'
    # Root directory of your frontend code within the monorepo
    # Assuming your frontend is in 'client/'
    rootDir: client/
    buildCommand: npm install && npm run build
    publishPath: client/build # Or client/dist for Vite
    autoDeploy: true # Enable auto-deploy
    # plan: free

  - type: postgres
    name: my-portfolio-db # Name for your PostgreSQL database
    # Default plan is usually enough for free tier
    # plan: free