# portfoli/render.yaml

services:
  # Frontend Service (Static Site)
  - type: web # This is the correct type for both static sites and web services
    name: portfolio-app
    runtime: static # *** ADD THIS LINE *** - Tells Render this is a static site
    # env: node # REMOVE THIS LINE - not needed for static runtime
    # plan: free # Optional, defaults to free if available
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: client/build # This is valid ONLY when runtime: static is set

  # Backend Service (Node.js Web Service)
  - type: web # Correct type for a Node.js web service
    name: portfolio-app-server
    env: node # This indicates it's a Node.js environment
    # You could also use: runtime: node (alternative to env: node)
    # plan: free # Optional
    rootDir: server
    buildCommand: npm install
    startCommand: npm run migrate:latest && node src/app.js # Assuming you've set up migrations

